/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Faucet__factory } from "./Faucet__factory";
export { IERC20Extended__factory } from "./IERC20Extended__factory";
