/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IV4PositionManager,
  IV4PositionManagerInterface,
} from "../../../contracts/Liquidity.sol/IV4PositionManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "unlockData",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
    ],
    name: "modifyLiquidities",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IV4PositionManager__factory {
  static readonly abi = _abi;
  static createInterface(): IV4PositionManagerInterface {
    return new utils.Interface(_abi) as IV4PositionManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IV4PositionManager {
    return new Contract(address, _abi, signerOrProvider) as IV4PositionManager;
  }
}
