/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  BeforeSwapDeltaLibrary,
  BeforeSwapDeltaLibraryInterface,
} from "../../../types/BeforeSwapDelta.sol/BeforeSwapDeltaLibrary";

const _abi = [
  {
    inputs: [],
    name: "ZERO_DELTA",
    outputs: [
      {
        internalType: "BeforeSwapDelta",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523460175760759081601d823930815050f35b600080fdfe6080806040526004361015601257600080fd5b60003560e01c6391cb466914602657600080fd5b6000366003190112603a5780600060209252f35b600080fdfea2646970667358221220b716b41d45bf2f97aa4b997f8966c15eb115ed75779b4ca319ca68f4c68975eb64736f6c634300081c0033";

type BeforeSwapDeltaLibraryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BeforeSwapDeltaLibraryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BeforeSwapDeltaLibrary__factory extends ContractFactory {
  constructor(...args: BeforeSwapDeltaLibraryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<BeforeSwapDeltaLibrary> {
    return super.deploy(overrides || {}) as Promise<BeforeSwapDeltaLibrary>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): BeforeSwapDeltaLibrary {
    return super.attach(address) as BeforeSwapDeltaLibrary;
  }
  override connect(signer: Signer): BeforeSwapDeltaLibrary__factory {
    return super.connect(signer) as BeforeSwapDeltaLibrary__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BeforeSwapDeltaLibraryInterface {
    return new utils.Interface(_abi) as BeforeSwapDeltaLibraryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BeforeSwapDeltaLibrary {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as BeforeSwapDeltaLibrary;
  }
}
