/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  BeforeSwapDeltaLibrary,
  BeforeSwapDeltaLibraryInterface,
} from "../../../types/BeforeSwapDelta.sol/BeforeSwapDeltaLibrary";

const _abi = [
  {
    inputs: [],
    name: "ZERO_DELTA",
    outputs: [
      {
        internalType: "BeforeSwapDelta",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60e3610051600b82828239805160001a6073146044577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c806391cb4669146038575b600080fd5b603e6052565b604051604991906094565b60405180910390f35b600081565b6000819050919050565b6000819050919050565b60006080607c6078846057565b6061565b6057565b9050919050565b608e81606b565b82525050565b600060208201905060a760008301846087565b9291505056fea264697066735822122002fee844067dbc61a1ad4281ab9f1c70368524bc73d1e91b93f4895c507ca30164736f6c634300081c0033";

type BeforeSwapDeltaLibraryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BeforeSwapDeltaLibraryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BeforeSwapDeltaLibrary__factory extends ContractFactory {
  constructor(...args: BeforeSwapDeltaLibraryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<BeforeSwapDeltaLibrary> {
    return super.deploy(overrides || {}) as Promise<BeforeSwapDeltaLibrary>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): BeforeSwapDeltaLibrary {
    return super.attach(address) as BeforeSwapDeltaLibrary;
  }
  override connect(signer: Signer): BeforeSwapDeltaLibrary__factory {
    return super.connect(signer) as BeforeSwapDeltaLibrary__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BeforeSwapDeltaLibraryInterface {
    return new utils.Interface(_abi) as BeforeSwapDeltaLibraryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BeforeSwapDeltaLibrary {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as BeforeSwapDeltaLibrary;
  }
}
