/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as faucetSol from "./Faucet.sol";
export type { faucetSol };
export type { LiquidityMining } from "./LiquidityMining";
export type { PriceOracle } from "./PriceOracle";
export type { SimpleDEX } from "./SimpleDEX";
export type { Token } from "./Token";
