/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace Faucet {
  export type FaucetHistoryStruct = {
    user: PromiseOrValue<string>;
    token: PromiseOrValue<string>;
    amount: PromiseOrValue<BigNumberish>;
    timestamp: PromiseOrValue<BigNumberish>;
    blockNumber: PromiseOrValue<BigNumberish>;
  };

  export type FaucetHistoryStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    user: string;
    token: string;
    amount: BigNumber;
    timestamp: BigNumber;
    blockNumber: BigNumber;
  };
}

export interface FaucetInterface extends utils.Interface {
  functions: {
    "FAUCET_COOLDOWN()": FunctionFragment;
    "addToken(address)": FunctionFragment;
    "emergencyWithdraw(address,uint256)": FunctionFragment;
    "faucetAmounts(address)": FunctionFragment;
    "faucetHistory(uint256)": FunctionFragment;
    "getAllUserFaucetHistory(address)": FunctionFragment;
    "getFaucetDetails(uint256)": FunctionFragment;
    "getSupportedTokens()": FunctionFragment;
    "getTimeUntilNextFaucet(address)": FunctionFragment;
    "getTokenInfo(address)": FunctionFragment;
    "getTotalFaucetCount()": FunctionFragment;
    "getUserFaucetCount(address)": FunctionFragment;
    "getUserFaucetHistory(address,uint256,uint256)": FunctionFragment;
    "lastFaucetTime(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "removeToken(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "requestAllFaucets()": FunctionFragment;
    "requestFaucet(address)": FunctionFragment;
    "supportedTokens(uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateFaucetAmount(address,uint256)": FunctionFragment;
    "userFaucetIndices(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "FAUCET_COOLDOWN"
      | "addToken"
      | "emergencyWithdraw"
      | "faucetAmounts"
      | "faucetHistory"
      | "getAllUserFaucetHistory"
      | "getFaucetDetails"
      | "getSupportedTokens"
      | "getTimeUntilNextFaucet"
      | "getTokenInfo"
      | "getTotalFaucetCount"
      | "getUserFaucetCount"
      | "getUserFaucetHistory"
      | "lastFaucetTime"
      | "owner"
      | "removeToken"
      | "renounceOwnership"
      | "requestAllFaucets"
      | "requestFaucet"
      | "supportedTokens"
      | "transferOwnership"
      | "updateFaucetAmount"
      | "userFaucetIndices"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "FAUCET_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "faucetAmounts",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "faucetHistory",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllUserFaucetHistory",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFaucetDetails",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupportedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTimeUntilNextFaucet",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenInfo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalFaucetCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserFaucetCount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserFaucetHistory",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "lastFaucetTime",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestAllFaucets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestFaucet",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFaucetAmount",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "userFaucetIndices",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "FAUCET_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "faucetAmounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "faucetHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllUserFaucetHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFaucetDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimeUntilNextFaucet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalFaucetCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserFaucetCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserFaucetHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastFaucetTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestAllFaucets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestFaucet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFaucetAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userFaucetIndices",
    data: BytesLike
  ): Result;

  events: {
    "FaucetAmountUpdated(address,uint256)": EventFragment;
    "FaucetUsed(address,address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "TokenAdded(address,uint256)": EventFragment;
    "TokenRemoved(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FaucetAmountUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FaucetUsed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenRemoved"): EventFragment;
}

export interface FaucetAmountUpdatedEventObject {
  token: string;
  newAmount: BigNumber;
}
export type FaucetAmountUpdatedEvent = TypedEvent<
  [string, BigNumber],
  FaucetAmountUpdatedEventObject
>;

export type FaucetAmountUpdatedEventFilter =
  TypedEventFilter<FaucetAmountUpdatedEvent>;

export interface FaucetUsedEventObject {
  user: string;
  token: string;
  amount: BigNumber;
}
export type FaucetUsedEvent = TypedEvent<
  [string, string, BigNumber],
  FaucetUsedEventObject
>;

export type FaucetUsedEventFilter = TypedEventFilter<FaucetUsedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface TokenAddedEventObject {
  token: string;
  amount: BigNumber;
}
export type TokenAddedEvent = TypedEvent<
  [string, BigNumber],
  TokenAddedEventObject
>;

export type TokenAddedEventFilter = TypedEventFilter<TokenAddedEvent>;

export interface TokenRemovedEventObject {
  token: string;
}
export type TokenRemovedEvent = TypedEvent<[string], TokenRemovedEventObject>;

export type TokenRemovedEventFilter = TypedEventFilter<TokenRemovedEvent>;

export interface Faucet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FaucetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    FAUCET_COOLDOWN(overrides?: CallOverrides): Promise<[BigNumber]>;

    addToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    emergencyWithdraw(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    faucetAmounts(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    faucetHistory(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, BigNumber, BigNumber] & {
        user: string;
        token: string;
        amount: BigNumber;
        timestamp: BigNumber;
        blockNumber: BigNumber;
      }
    >;

    getAllUserFaucetHistory(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[Faucet.FaucetHistoryStructOutput[]]>;

    getFaucetDetails(
      faucetIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[Faucet.FaucetHistoryStructOutput]>;

    getSupportedTokens(overrides?: CallOverrides): Promise<[string[]]>;

    getTimeUntilNextFaucet(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTokenInfo(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string] & {
        amount: BigNumber;
        symbol: string;
        name: string;
      }
    >;

    getTotalFaucetCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    getUserFaucetCount(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getUserFaucetHistory(
      user: PromiseOrValue<string>,
      start: PromiseOrValue<BigNumberish>,
      count: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[Faucet.FaucetHistoryStructOutput[]]>;

    lastFaucetTime(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    removeToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    requestAllFaucets(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    requestFaucet(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportedTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateFaucetAmount(
      token: PromiseOrValue<string>,
      newAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    userFaucetIndices(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  FAUCET_COOLDOWN(overrides?: CallOverrides): Promise<BigNumber>;

  addToken(
    token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  emergencyWithdraw(
    token: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  faucetAmounts(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  faucetHistory(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, BigNumber, BigNumber] & {
      user: string;
      token: string;
      amount: BigNumber;
      timestamp: BigNumber;
      blockNumber: BigNumber;
    }
  >;

  getAllUserFaucetHistory(
    user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<Faucet.FaucetHistoryStructOutput[]>;

  getFaucetDetails(
    faucetIndex: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<Faucet.FaucetHistoryStructOutput>;

  getSupportedTokens(overrides?: CallOverrides): Promise<string[]>;

  getTimeUntilNextFaucet(
    user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTokenInfo(
    token: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string] & {
      amount: BigNumber;
      symbol: string;
      name: string;
    }
  >;

  getTotalFaucetCount(overrides?: CallOverrides): Promise<BigNumber>;

  getUserFaucetCount(
    user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getUserFaucetHistory(
    user: PromiseOrValue<string>,
    start: PromiseOrValue<BigNumberish>,
    count: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<Faucet.FaucetHistoryStructOutput[]>;

  lastFaucetTime(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  removeToken(
    token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  requestAllFaucets(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  requestFaucet(
    token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportedTokens(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateFaucetAmount(
    token: PromiseOrValue<string>,
    newAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  userFaucetIndices(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    FAUCET_COOLDOWN(overrides?: CallOverrides): Promise<BigNumber>;

    addToken(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    emergencyWithdraw(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    faucetAmounts(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    faucetHistory(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, BigNumber, BigNumber] & {
        user: string;
        token: string;
        amount: BigNumber;
        timestamp: BigNumber;
        blockNumber: BigNumber;
      }
    >;

    getAllUserFaucetHistory(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<Faucet.FaucetHistoryStructOutput[]>;

    getFaucetDetails(
      faucetIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<Faucet.FaucetHistoryStructOutput>;

    getSupportedTokens(overrides?: CallOverrides): Promise<string[]>;

    getTimeUntilNextFaucet(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenInfo(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string] & {
        amount: BigNumber;
        symbol: string;
        name: string;
      }
    >;

    getTotalFaucetCount(overrides?: CallOverrides): Promise<BigNumber>;

    getUserFaucetCount(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserFaucetHistory(
      user: PromiseOrValue<string>,
      start: PromiseOrValue<BigNumberish>,
      count: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<Faucet.FaucetHistoryStructOutput[]>;

    lastFaucetTime(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    removeToken(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    requestAllFaucets(overrides?: CallOverrides): Promise<void>;

    requestFaucet(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    supportedTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateFaucetAmount(
      token: PromiseOrValue<string>,
      newAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    userFaucetIndices(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "FaucetAmountUpdated(address,uint256)"(
      token?: PromiseOrValue<string> | null,
      newAmount?: null
    ): FaucetAmountUpdatedEventFilter;
    FaucetAmountUpdated(
      token?: PromiseOrValue<string> | null,
      newAmount?: null
    ): FaucetAmountUpdatedEventFilter;

    "FaucetUsed(address,address,uint256)"(
      user?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      amount?: null
    ): FaucetUsedEventFilter;
    FaucetUsed(
      user?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      amount?: null
    ): FaucetUsedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "TokenAdded(address,uint256)"(
      token?: PromiseOrValue<string> | null,
      amount?: null
    ): TokenAddedEventFilter;
    TokenAdded(
      token?: PromiseOrValue<string> | null,
      amount?: null
    ): TokenAddedEventFilter;

    "TokenRemoved(address)"(
      token?: PromiseOrValue<string> | null
    ): TokenRemovedEventFilter;
    TokenRemoved(
      token?: PromiseOrValue<string> | null
    ): TokenRemovedEventFilter;
  };

  estimateGas: {
    FAUCET_COOLDOWN(overrides?: CallOverrides): Promise<BigNumber>;

    addToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    emergencyWithdraw(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    faucetAmounts(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    faucetHistory(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllUserFaucetHistory(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFaucetDetails(
      faucetIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSupportedTokens(overrides?: CallOverrides): Promise<BigNumber>;

    getTimeUntilNextFaucet(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenInfo(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalFaucetCount(overrides?: CallOverrides): Promise<BigNumber>;

    getUserFaucetCount(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserFaucetHistory(
      user: PromiseOrValue<string>,
      start: PromiseOrValue<BigNumberish>,
      count: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastFaucetTime(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    removeToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    requestAllFaucets(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    requestFaucet(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportedTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateFaucetAmount(
      token: PromiseOrValue<string>,
      newAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    userFaucetIndices(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    FAUCET_COOLDOWN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    emergencyWithdraw(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    faucetAmounts(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    faucetHistory(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllUserFaucetHistory(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFaucetDetails(
      faucetIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSupportedTokens(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTimeUntilNextFaucet(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokenInfo(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalFaucetCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserFaucetCount(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserFaucetHistory(
      user: PromiseOrValue<string>,
      start: PromiseOrValue<BigNumberish>,
      count: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lastFaucetTime(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    requestAllFaucets(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    requestFaucet(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportedTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateFaucetAmount(
      token: PromiseOrValue<string>,
      newAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    userFaucetIndices(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
