/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IExttload, IExttloadInterface } from "../../interfaces/IExttload";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "slots",
        type: "bytes32[]",
      },
    ],
    name: "exttload",
    outputs: [
      {
        internalType: "bytes32[]",
        name: "values",
        type: "bytes32[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "slot",
        type: "bytes32",
      },
    ],
    name: "exttload",
    outputs: [
      {
        internalType: "bytes32",
        name: "value",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IExttload__factory {
  static readonly abi = _abi;
  static createInterface(): IExttloadInterface {
    return new utils.Interface(_abi) as IExttloadInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IExttload {
    return new Contract(address, _abi, signerOrProvider) as IExttload;
  }
}
