/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IUnlockCallback,
  IUnlockCallbackInterface,
} from "../../../interfaces/callback/IUnlockCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "unlockCallback",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IUnlockCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IUnlockCallbackInterface {
    return new utils.Interface(_abi) as IUnlockCallbackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUnlockCallback {
    return new Contract(address, _abi, signerOrProvider) as IUnlockCallback;
  }
}
