/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  CurrencyLibrary,
  CurrencyLibraryInterface,
} from "../../../types/Currency.sol/CurrencyLibrary";

const _abi = [
  {
    inputs: [],
    name: "ERC20TransferFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "NativeTransferFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "ADDRESS_ZERO",
    outputs: [
      {
        internalType: "Currency",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523460175760759081601d823930815050f35b600080fdfe6080806040526004361015601257600080fd5b60003560e01c6366e7950914602657600080fd5b6000366003190112603a5780600060209252f35b600080fdfea264697066735822122077411f2a18a589227525148df362cc3464e3e12ec5710cf350e2aae74bc7014464736f6c634300081c0033";

type CurrencyLibraryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CurrencyLibraryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CurrencyLibrary__factory extends ContractFactory {
  constructor(...args: CurrencyLibraryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<CurrencyLibrary> {
    return super.deploy(overrides || {}) as Promise<CurrencyLibrary>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): CurrencyLibrary {
    return super.attach(address) as CurrencyLibrary;
  }
  override connect(signer: Signer): CurrencyLibrary__factory {
    return super.connect(signer) as CurrencyLibrary__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CurrencyLibraryInterface {
    return new utils.Interface(_abi) as CurrencyLibraryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CurrencyLibrary {
    return new Contract(address, _abi, signerOrProvider) as CurrencyLibrary;
  }
}
